name: steps
on:
  push:
    branches: [ master ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: My first step
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Boris
        MIDDLE_NAME: Hermann
        LAST_NAME: Tibago
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
    - name: My second step
      if: success()
      run: echo "The previous step has finished successfully"
    - name: My third step
      uses: actions/checkout@v1
      with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/ # if your publishing your package to npm or github package repo
    
