name: steps
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: My first step
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Boris
        MIDDLE_NAME: Hermann
        LAST_NAME: Tibago
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
    - name: My second step
      if: success()
      run: echo "The previous step has finished successfully"
    - name: My third step
      uses: actions/checkout@v1
      with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/ # if your publishing your package to npm or github package repo
    - name: my fourth step
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users first issue"
        pr-message: "Message that willbe displayed on users first pr"
